# 服务器开放给客户端的frp端口
bind_port = 57000
# http端口
vhost_http_port = 8080
# https端口
vhost_https_port = 8081
dashboard_addr = 0.0.0.0
# 控制面板端口,用户名,密码
dashboard_port = 57500
dashboard_user = YokiiroBW
dashboard_pwd = telunsu112233
# frps服务token,拥有此token的客户端才允许连接
token = 417454
